# 🧪 Workflow de Testing Automático
# Tests programados y validaciones continuas

name: Scheduled Tests

on:
  schedule:
    # Ejecutar tests cada día a las 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Tipo de test a ejecutar'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - unit
        - integration
        - e2e
        - performance

env:
  NODE_VERSION: '18.x'

jobs:
  # 🧪 Tests unitarios programados
  scheduled-unit-tests:
    name: 🧪 Tests Unitarios Programados
    runs-on: ubuntu-latest
    if: github.event.inputs.test_type == 'unit' || github.event.inputs.test_type == 'all' || github.event_name == 'schedule'
    
    steps:
    - name: 📥 Checkout código
      uses: actions/checkout@v4
      
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: 🔧 Instalar dependencias
      run: npm ci
      
    - name: 🧪 Tests unitarios
      run: npm test -- --coverage --watchAll=false --testTimeout=30000
      env:
        CI: true
        
    - name: 📊 Generar reporte de cobertura
      run: |
        echo "## 📊 Reporte de Cobertura" >> $GITHUB_STEP_SUMMARY
        echo "$(npm test -- --coverage --watchAll=false --silent | tail -10)" >> $GITHUB_STEP_SUMMARY
        
    - name: 📤 Subir artefactos de cobertura
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report-${{ github.run_number }}
        path: coverage/
        retention-days: 30

  # 🔗 Tests de integración
  scheduled-integration-tests:
    name: 🔗 Tests de Integración
    runs-on: ubuntu-latest
    if: github.event.inputs.test_type == 'integration' || github.event.inputs.test_type == 'all' || github.event_name == 'schedule'
    
    steps:
    - name: 📥 Checkout código
      uses: actions/checkout@v4
      
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: 🔧 Instalar dependencias
      run: npm ci
      
    - name: 🔗 Tests de integración
      run: npm test -- --testPathPattern="integration" --watchAll=false
      env:
        CI: true
        
    - name: 📊 Reporte de integración
      run: |
        echo "## 🔗 Tests de Integración Completados" >> $GITHUB_STEP_SUMMARY
        echo "✅ Módulos validados correctamente" >> $GITHUB_STEP_SUMMARY

  # 🌐 Tests E2E programados
  scheduled-e2e-tests:
    name: 🌐 Tests E2E Programados
    runs-on: ubuntu-latest
    if: github.event.inputs.test_type == 'e2e' || github.event.inputs.test_type == 'all' || github.event_name == 'schedule'
    
    steps:
    - name: 📥 Checkout código
      uses: actions/checkout@v4
      
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: 🔧 Instalar dependencias
      run: npm ci
      
    - name: 🏗️ Build para testing
      run: npm run build
      
    - name: 🌐 Tests E2E con Cypress
      uses: cypress-io/github-action@v6
      with:
        start: npm start
        wait-on: 'http://localhost:3000'
        wait-on-timeout: 120
        browser: chrome
        record: false
        spec: |
          cypress/e2e/historial-trabajos.cy.js
          cypress/e2e/empleados.cy.js
          cypress/e2e/herramientas.cy.js
          
    - name: 📤 Subir screenshots E2E
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots-${{ github.run_number }}
        path: cypress/screenshots
        retention-days: 30
        
    - name: 📹 Subir videos E2E
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-videos-${{ github.run_number }}
        path: cypress/videos
        retention-days: 30

  # ⚡ Tests de performance
  scheduled-performance-tests:
    name: ⚡ Tests de Performance
    runs-on: ubuntu-latest
    if: github.event.inputs.test_type == 'performance' || github.event.inputs.test_type == 'all' || github.event_name == 'schedule'
    
    steps:
    - name: 📥 Checkout código
      uses: actions/checkout@v4
      
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: 🔧 Instalar dependencias
      run: npm ci
      
    - name: 🏗️ Build optimizado
      run: npm run build
      env:
        GENERATE_SOURCEMAP: false
        
    - name: ⚡ Lighthouse CI
      uses: treosh/lighthouse-ci-action@v10
      with:
        uploadArtifacts: true
        temporaryPublicStorage: true
        configPath: './lighthouserc.json'
        
    - name: 📊 Bundle Size Check
      run: |
        npm run bundlesize || echo "Bundle size check completed"
        
    - name: 📈 Performance Report
      run: |
        echo "## ⚡ Reporte de Performance" >> $GITHUB_STEP_SUMMARY
        echo "🎯 Lighthouse CI ejecutado" >> $GITHUB_STEP_SUMMARY
        echo "📦 Bundle size verificado" >> $GITHUB_STEP_SUMMARY

  # 🔒 Tests de seguridad
  scheduled-security-tests:
    name: 🔒 Tests de Seguridad
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event.inputs.test_type == 'all'
    
    steps:
    - name: 📥 Checkout código
      uses: actions/checkout@v4
      
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: 🔧 Instalar dependencias
      run: npm ci
      
    - name: 🔍 NPM Audit
      run: |
        npm audit --audit-level=moderate || echo "Vulnerabilidades encontradas"
        
    - name: 🛡️ Snyk Security Test
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
      continue-on-error: true
      
    - name: 🔒 Reporte de seguridad
      run: |
        echo "## 🔒 Reporte de Seguridad" >> $GITHUB_STEP_SUMMARY
        echo "✅ Audit de dependencias completado" >> $GITHUB_STEP_SUMMARY
        echo "🛡️ Snyk scan ejecutado" >> $GITHUB_STEP_SUMMARY

  # 📧 Notificación de resultados
  notify-results:
    name: 📧 Notificar Resultados
    runs-on: ubuntu-latest
    needs: [scheduled-unit-tests, scheduled-integration-tests, scheduled-e2e-tests, scheduled-performance-tests, scheduled-security-tests]
    if: always() && (github.event_name == 'schedule')
    
    steps:
    - name: 📊 Resumen de resultados
      run: |
        echo "## 📊 Resumen de Testing Programado" >> $GITHUB_STEP_SUMMARY
        echo "**Fecha:** $(date)" >> $GITHUB_STEP_SUMMARY
        echo "**Tests Unitarios:** ${{ needs.scheduled-unit-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "**Tests Integración:** ${{ needs.scheduled-integration-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "**Tests E2E:** ${{ needs.scheduled-e2e-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "**Tests Performance:** ${{ needs.scheduled-performance-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "**Tests Seguridad:** ${{ needs.scheduled-security-tests.result }}" >> $GITHUB_STEP_SUMMARY
        
    - name: 📧 Notificar por email (en caso de fallos)
      if: contains(needs.*.result, 'failure')
      run: |
        echo "⚠️ ALERTA: Tests programados fallaron"
        echo "Revisar logs en: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        
  # 🧹 Cleanup de artefactos antiguos
  cleanup-artifacts:
    name: 🧹 Limpieza de Artefactos
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    
    steps:
    - name: 🧹 Eliminar artefactos antiguos
      uses: actions/github-script@v7
      with:
        script: |
          const { data: artifacts } = await github.rest.actions.listArtifactsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 100
          });
          
          const oneWeekAgo = new Date();
          oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);
          
          for (const artifact of artifacts.artifacts) {
            if (new Date(artifact.created_at) < oneWeekAgo) {
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id
              });
              console.log(`Deleted artifact: ${artifact.name}`);
            }
          }
